# GitHub Actions CI/CD pipeline script for automating the build and deployment process
# for a Dockerized application
name: Build and Deploy

# the trigger, whenever changes are pushed
on:
  push:
    branches:
      - master

# GitHub Actions porvides a runner (essentially a VM) on which the jobs are executed on
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

# Follow the script from ./docker-compose.yml
    - name: Build Docker images using docker-compose
      run: docker-compose build

# Upload the images to DockerHub
    - name: Push Docker images
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker-compose push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
